# Generated by Django 2.1 on 2018-08-08 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Cult', max_length=25)),
                ('type', models.CharField(default='none', max_length=5)),
                ('money', models.IntegerField(default=5000)),
                ('reputation', models.IntegerField(default=0)),
                ('contacts', models.TextField(default='[{id: "anonymous", card: "1.0.0"}]')),
                ('inventory', models.TextField(default='[]')),
                ('research', models.TextField(default='[]')),
                ('headquarters', models.TextField(default='[]')),
            ],
        ),
        migrations.CreateModel(
            name='WarfareGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WarfarePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.WarfareGame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cult',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.WarfarePlayer'),
        ),
    ]
