# Generated by Django 2.1 on 2018-08-11 19:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cult',
            name='contacts',
            field=models.TextField(default='[{"id": "anonymous", "card": "1.0.0"}]'),
        ),
        migrations.AlterField(
            model_name='cult',
            name='headquarters',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
