# Generated by Django 2.1 on 2018-08-11 19:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20180811_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cult',
            name='headquarters',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
