# Generated by Django 2.1 on 2018-08-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20180811_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cult',
            name='money',
            field=models.BigIntegerField(default=5000),
        ),
    ]
