# Generated by Django 2.1 on 2018-08-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20180812_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='cult',
            name='marketplace',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='cult',
            name='members',
            field=models.TextField(default='[]'),
        ),
    ]
