# Generated by Django 2.1 on 2018-08-13 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20180813_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('job_id', models.SmallIntegerField(default=0)),
                ('skills', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cult',
            name='members',
        ),
        migrations.AddField(
            model_name='member',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Cult'),
        ),
    ]
