# Generated by Django 2.1 on 2018-08-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20180813_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='intelligence',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='social',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='stealth',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='strength',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
