# Generated by Django 2.1 on 2018-08-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20180813_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='owner',
            new_name='cult',
        ),
    ]
