# Generated by Django 2.1 on 2018-08-13 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20180813_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='job_id',
            field=models.SmallIntegerField(default=0, help_text='0 = no job, 1 = recruiting, 2 = researching, 3 = guarding'),
        ),
        migrations.AlterField(
            model_name='member',
            name='skills',
            field=models.TextField(help_text='For example: [{name: "Lockpicker", level: 2}, {name: "Blackmailer", level: 1}]'),
        ),
    ]
