# Generated by Django 2.1 on 2018-08-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20180813_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='loyalty',
            field=models.SmallIntegerField(default=50),
            preserve_default=False,
        ),
    ]
