# Generated by Django 2.1 on 2018-08-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_member_loyalty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='member',
            name='supervisor_id',
            field=models.IntegerField(default=0),
        ),
    ]
