# Generated by Django 2.1 on 2018-08-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20180814_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='specialization',
            field=models.CharField(default='technician', help_text='Specialization name followed by a <b>/</b> and then the level, e.g. "Technician/3".', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cult',
            name='contacts',
            field=models.TextField(default='[{"id": "anonymous", "card": "1.0.0"}]', help_text='For example: [{"id": "anonymous", "card": "1.4.0"}, {"id": "assistant", "card": "1.0.1}]'),
        ),
        migrations.AlterField(
            model_name='cult',
            name='headquarters',
            field=models.TextField(default='[]', help_text='For example: ["windowbars", "cctv"]'),
        ),
        migrations.AlterField(
            model_name='member',
            name='job_id',
            field=models.SmallIntegerField(default=0, help_text='0 = no job, 1 = recruiting, 2 = researching, 3 = guarding.'),
        ),
        migrations.AlterField(
            model_name='member',
            name='skills',
            field=models.TextField(help_text='For example: ["recruitmentstrategies", "silentwalking"]'),
        ),
    ]
