# Generated by Django 2.1 on 2018-08-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20180814_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='skills',
            field=models.TextField(default='[]', help_text='For example: ["recruitmentstrategies", "silentwalking"]'),
        ),
        migrations.AlterField(
            model_name='member',
            name='supervisor_id',
            field=models.IntegerField(default=-1),
        ),
    ]
