# Generated by Django 2.1 on 2018-08-15 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20180814_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='supervisor_id',
        ),
        migrations.AddField(
            model_name='member',
            name='job',
            field=models.CharField(default='none', help_text='Options: none, recruiting, researching, guarding, pickpocketing, spying.', max_length=15),
        ),
        migrations.AddField(
            model_name='member',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Member'),
        ),
    ]
