# Generated by Django 2.1 on 2018-08-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_auto_20180815_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='wage',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
