# Generated by Django 2.1 on 2018-08-15 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_member_wage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Member'),
        ),
    ]
