# Generated by Django 2.1 on 2018-08-15 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_auto_20180815_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='cult',
            new_name='owner',
        ),
    ]
