# Generated by Django 2.1 on 2018-08-17 17:25

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_member_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='cult',
            name='last_check',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.datetime_safe.datetime.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cult',
            name='contacts',
            field=models.TextField(default='[{"id": "anonymous", "card": "1.0.0"}]', help_text='For example: [{"id": "anonymous", "card": "1.4.0"}, {"id": "assistant", "card": "1.0.1}]<br>                  Assistant added at anonymous "1.3.0". Mafioso added at assistant "1.1.2".'),
        ),
    ]
