# Generated by Django 2.1 on 2018-08-17 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_auto_20180817_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cult',
            name='last_check',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
