# Generated by Django 2.1 on 2018-08-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_auto_20180820_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='cult',
            name='research_points',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='cult',
            name='recruitment_target',
            field=models.IntegerField(default=25),
        ),
    ]
