# Generated by Django 2.1 on 2018-09-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_remove_cult_recruitment_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cult',
            name='inventory',
            field=models.TextField(default='{}'),
        ),
    ]
