# Generated by Django 2.1 on 2018-12-04 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_auto_20180916_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Underworld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.CharField(max_length=32)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('time', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Cult')),
            ],
        ),
    ]
